### ISSUE TITLE
Contributing 

### ISSUE THREAD

**Issue by kyleknighted** [alexzaworski/senseis-top#1]
Are you looking for contributors? Do you have a list of wanted or upcoming features or most asked for?

**Comment by alexzaworski** [comment]
Ah! One huge thing I missed— being able to reset your life total is totally necessary. I'd imagine we'll need some sort of settings tab to choose a default total, and then a reset button somewhere on the main screen. That could be a good one to tackle.

**Comment by kyleknighted** [comment]
Communication question: do you prefer Issues, or would you be open to [Gitter](https://gitter.im/) or [Discord](https://discordapp.com/) or something else?

**Comment by alexzaworski** [comment]
I don't have any experience with Gitter and I've only minimally used Discord. For now I'd rather stick to issues, but if they start getting too conversational/difficult to parse I'm open to alternatives.
