### ISSUE TITLE
Add functionality - Ability to change color

### ISSUE THREAD

**Issue by MeesterRoboto** [alexzaworski/senseis-top#39]
I discovered your app when searching for a solution for decentralized life counters that I could incorporate into twitch streams broadcasting webcam magic. Right now, the app as-is is perfect for incorporating remote life counters into our streams without fuss for our competitors. 

I would like to request the ability to customize the color of the life counter app to better incorporate the life counter into our streams as not every overlay we use will go well with purple. 

Perhaps we are 4 years too late, but this app solves a ton of issues in a simple manner.

**Comment by alexzaworski** [comment]
Hi :)

I haven't really worked on this in a while and haven't played magic in years, not likely something I'll add any time soon.

Depending on how the integration works you could maybe use an extension to color things yourself? eg https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en-US

Not ideal but I suspect this'd work for your use case.

**Comment by MeesterRoboto** [comment]
Appreciate the quick reply! 

After some quick tests, Stylebot is a great solution. I appreciate the suggestion. 

Also wanted to take the time to say thanks for keeping this project online. This is likely to become a tool we come to depend on.

**Comment by alexzaworski** [comment]
Glad it works for you! Happy to keep the lights on 🙂
